#include <Windows.h>


namespace xsip {
	namespace server {
		namespace CMapInfo {
			 uintptr_t m_iBuyingStatus = 0x4e0; // int32
			 uintptr_t m_flBombRadius = 0x4e4; // float32
			 uintptr_t m_iPetPopulation = 0x4e8; // int32
			 uintptr_t m_bUseNormalSpawnsForDM = 0x4ec; // bool
			 uintptr_t m_bDisableAutoGeneratedDMSpawns = 0x4ed; // bool
			 uintptr_t m_flBotMaxVisionDistance = 0x4f0; // float32
			 uintptr_t m_iHostageCount = 0x4f4; // int32
			 uintptr_t m_bFadePlayerVisibilityFarZ = 0x4f8; // bool
			 uintptr_t m_bRainTraceToSkyEnabled = 0x4f9; // bool
		}
	}
}
