#include <Windows.h>


namespace xsip {
	namespace server {
		namespace CMapInfo {
			 uintptr_t m_iBuyingStatus = 0x4e0;
			 uintptr_t m_flBombRadius = 0x4e4;
			 uintptr_t m_iPetPopulation = 0x4e8;
			 uintptr_t m_bUseNormalSpawnsForDM = 0x4ec;
			 uintptr_t m_bDisableAutoGeneratedDMSpawns = 0x4ed;
			 uintptr_t m_flBotMaxVisionDistance = 0x4f0;
			 uintptr_t m_iHostageCount = 0x4f4;
			 uintptr_t m_bFadePlayerVisibilityFarZ = 0x4f8;
			 uintptr_t m_bRainTraceToSkyEnabled = 0x4f9;
		}
	}
}
