#include <Windows.h>


namespace xsip {
	namespace server {
		namespace CSceneEntity {
			 uintptr_t m_iszSceneFile = 0x4e8;
			 uintptr_t m_iszResumeSceneFile = 0x4f0;
			 uintptr_t m_iszTarget1 = 0x4f8;
			 uintptr_t m_iszTarget2 = 0x500;
			 uintptr_t m_iszTarget3 = 0x508;
			 uintptr_t m_iszTarget4 = 0x510;
			 uintptr_t m_iszTarget5 = 0x518;
			 uintptr_t m_iszTarget6 = 0x520;
			 uintptr_t m_iszTarget7 = 0x528;
			 uintptr_t m_iszTarget8 = 0x530;
			 uintptr_t m_hTarget1 = 0x538;
			 uintptr_t m_hTarget2 = 0x53c;
			 uintptr_t m_hTarget3 = 0x540;
			 uintptr_t m_hTarget4 = 0x544;
			 uintptr_t m_hTarget5 = 0x548;
			 uintptr_t m_hTarget6 = 0x54c;
			 uintptr_t m_hTarget7 = 0x550;
			 uintptr_t m_hTarget8 = 0x554;
			 uintptr_t m_sTargetAttachment = 0x558;
			 uintptr_t m_bIsPlayingBack = 0x560;
			 uintptr_t m_bPaused = 0x561;
			 uintptr_t m_bMultiplayer = 0x562;
			 uintptr_t m_bAutogenerated = 0x563;
			 uintptr_t m_flForceClientTime = 0x564;
			 uintptr_t m_flCurrentTime = 0x568;
			 uintptr_t m_flFrameTime = 0x56c;
			 uintptr_t m_bCancelAtNextInterrupt = 0x570;
			 uintptr_t m_fPitch = 0x574;
			 uintptr_t m_bAutomated = 0x578;
			 uintptr_t m_nAutomatedAction = 0x57c;
			 uintptr_t m_flAutomationDelay = 0x580;
			 uintptr_t m_flAutomationTime = 0x584;
			 uintptr_t m_hWaitingForThisResumeScene = 0x588;
			 uintptr_t m_bWaitingForResumeScene = 0x58c;
			 uintptr_t m_bPausedViaInput = 0x58d;
			 uintptr_t m_bPauseAtNextInterrupt = 0x58e;
			 uintptr_t m_bWaitingForActor = 0x58f;
			 uintptr_t m_bWaitingForInterrupt = 0x590;
			 uintptr_t m_bInterruptedActorsScenes = 0x591;
			 uintptr_t m_bBreakOnNonIdle = 0x592;
			 uintptr_t m_bSceneFinished = 0x593;
			 uintptr_t m_hActorList = 0x598;
			 uintptr_t m_hRemoveActorList = 0x5b0;
			 uintptr_t m_nSceneFlushCounter = 0x5f8;
			 uintptr_t m_nSceneStringIndex = 0x5fc;
			 uintptr_t m_OnStart = 0x600;
			 uintptr_t m_OnCompletion = 0x628;
			 uintptr_t m_OnCanceled = 0x650;
			 uintptr_t m_OnPaused = 0x678;
			 uintptr_t m_OnResumed = 0x6a0;
			 uintptr_t m_OnTrigger = 0x6c8;
			 uintptr_t m_hInterruptScene = 0x9d8;
			 uintptr_t m_nInterruptCount = 0x9dc;
			 uintptr_t m_bSceneMissing = 0x9e0;
			 uintptr_t m_bInterrupted = 0x9e1;
			 uintptr_t m_bCompletedEarly = 0x9e2;
			 uintptr_t m_bInterruptSceneFinished = 0x9e3;
			 uintptr_t m_bRestoring = 0x9e4;
			 uintptr_t m_hNotifySceneCompletion = 0x9e8;
			 uintptr_t m_hListManagers = 0xa00;
			 uintptr_t m_iszSoundName = 0xa18;
			 uintptr_t m_iszSequenceName = 0xa20;
			 uintptr_t m_hActor = 0xa28;
			 uintptr_t m_hActivator = 0xa2c;
			 uintptr_t m_BusyActor = 0xa30;
			 uintptr_t m_iPlayerDeathBehavior = 0xa34;
		}
	}
}
