#include <Windows.h>


namespace xsip {
	namespace client {
		namespace C_SceneEntity {
			 uintptr_t m_bIsPlayingBack = 0x570; // bool
			 uintptr_t m_bPaused = 0x571; // bool
			 uintptr_t m_bMultiplayer = 0x572; // bool
			 uintptr_t m_bAutogenerated = 0x573; // bool
			 uintptr_t m_flForceClientTime = 0x574; // float32
			 uintptr_t m_nSceneStringIndex = 0x578; // uint16
			 uintptr_t m_bClientOnly = 0x57a; // bool
			 uintptr_t m_hOwner = 0x57c; // CHandle< C_BaseFlex >
			 uintptr_t m_hActorList = 0x580; // C_NetworkUtlVectorBase< CHandle< C_BaseFlex > >
			 uintptr_t m_bWasPlaying = 0x598; // bool
			 uintptr_t m_QueuedEvents = 0x5a8; // CUtlVector< C_SceneEntity::QueuedEvents_t >
			 uintptr_t m_flCurrentTime = 0x5c0; // float32
		}
	}
}
