#include <Windows.h>


namespace xsip {
	namespace client {
		namespace C_SceneEntity {
			 uintptr_t m_bIsPlayingBack = 0x570;
			 uintptr_t m_bPaused = 0x571;
			 uintptr_t m_bMultiplayer = 0x572;
			 uintptr_t m_bAutogenerated = 0x573;
			 uintptr_t m_flForceClientTime = 0x574;
			 uintptr_t m_nSceneStringIndex = 0x578;
			 uintptr_t m_bClientOnly = 0x57a;
			 uintptr_t m_hOwner = 0x57c;
			 uintptr_t m_hActorList = 0x580;
			 uintptr_t m_bWasPlaying = 0x598;
			 uintptr_t m_QueuedEvents = 0x5a8;
			 uintptr_t m_flCurrentTime = 0x5c0;
		}
	}
}
