#include <Windows.h>


namespace xsip {
	namespace client {
		namespace CMapInfo {
			 uintptr_t m_iBuyingStatus = 0x568; // int32
			 uintptr_t m_flBombRadius = 0x56c; // float32
			 uintptr_t m_iPetPopulation = 0x570; // int32
			 uintptr_t m_bUseNormalSpawnsForDM = 0x574; // bool
			 uintptr_t m_bDisableAutoGeneratedDMSpawns = 0x575; // bool
			 uintptr_t m_flBotMaxVisionDistance = 0x578; // float32
			 uintptr_t m_iHostageCount = 0x57c; // int32
			 uintptr_t m_bFadePlayerVisibilityFarZ = 0x580; // bool
			 uintptr_t m_bRainTraceToSkyEnabled = 0x581; // bool
		}
	}
}
