#include <Windows.h>


namespace xsip {
	namespace client {
		namespace CMapInfo {
			 uintptr_t m_iBuyingStatus = 0x568;
			 uintptr_t m_flBombRadius = 0x56c;
			 uintptr_t m_iPetPopulation = 0x570;
			 uintptr_t m_bUseNormalSpawnsForDM = 0x574;
			 uintptr_t m_bDisableAutoGeneratedDMSpawns = 0x575;
			 uintptr_t m_flBotMaxVisionDistance = 0x578;
			 uintptr_t m_iHostageCount = 0x57c;
			 uintptr_t m_bFadePlayerVisibilityFarZ = 0x580;
			 uintptr_t m_bRainTraceToSkyEnabled = 0x581;
		}
	}
}
